pool_abi = [dict(inputs=[{"internalType": "address", "name": "_factoryV2", "trade_type": "address"},
                         {"internalType": "address", "name": "factoryV3", "trade_type": "address"},
                         {"internalType": "address", "name": "_positionManager", "trade_type": "address"},
                         {"internalType": "address", "name": "_WETH9", "trade_type": "address"}],
                 stateMutability="nonpayable", type="constructor"),
            {"inputs": [],
             "name": "WETH9",
             "outputs": [{"internalType": "address", "name": "", "trade_type": "address"}],
             "stateMutability": "view",
             "trade_type": "function"},
            {"inputs": [{"internalType": "address", "name": "token", "trade_type": "address"}],
             "name": "approveMax",
             "outputs": [],
             "stateMutability": "payable",
             "trade_type": "function"},
            {"inputs": [{"internalType": "address", "name": "token", "trade_type": "address"}],
             "name": "approveMaxMinusOne",
             "outputs": [],
             "stateMutability": "payable",
             "trade_type": "function"},
            {"inputs": [{"internalType": "address", "name": "token", "trade_type": "address"}],
             "name": "approveZeroThenMax",
             "outputs": [],
             "stateMutability": "payable",
             "trade_type": "function"},
            {"inputs": [{"internalType": "address", "name": "token", "trade_type": "address"}],
             "name": "approveZeroThenMaxMinusOne",
             "outputs": [],
             "stateMutability": "payable",
             "trade_type": "function"},
            {"inputs": [{"internalType": "bytes", "name": "data", "trade_type": "bytes"}],
             "name": "callPositionManager",
             "outputs": [{"internalType": "bytes", "name": "result", "trade_type": "bytes"}],
             "stateMutability": "payable",
             "trade_type": "function"},
            {"inputs": [{"internalType": "bytes[]", "name": "paths", "trade_type": "bytes[]"},
                        {"internalType": "uint128[]", "name": "amounts", "trade_type": "uint128[]"},
                        {"internalType": "uint24", "name": "maximumTickDivergence", "trade_type": "uint24"},
                        {"internalType": "uint32", "name": "secondsAgo", "trade_type": "uint32"}],
             "name": "checkOracleSlippage",
             "outputs": [],
             "stateMutability": "view",
             "trade_type": "function"},
            {"inputs": [{"internalType": "bytes", "name": "path", "trade_type": "bytes"},
                        {"internalType": "uint24", "name": "maximumTickDivergence", "trade_type": "uint24"},
                        {"internalType": "uint32", "name": "secondsAgo", "trade_type": "uint32"}],
             "name": "checkOracleSlippage",
             "outputs": [],
             "stateMutability": "view",
             "trade_type": "function"},
            {"inputs": [{"components": [{"internalType": "bytes", "name": "path", "trade_type": "bytes"},
                                        {"internalType": "address", "name": "recipient", "trade_type": "address"},
                                        {"internalType": "uint256", "name": "amountIn", "trade_type": "uint256"},
                                        {"internalType": "uint256", "name": "amountOutMinimum", "trade_type": "uint256"}],
                         "internalType": "struct IV3SwapRouter.ExactInputParams", "name": "params","trade_type": "tuple"}],
             "name": "exactInput",
             "outputs": [{"internalType": "uint256", "name": "amountOut", "trade_type": "uint256"}],
             "stateMutability": "payable",
             "trade_type": "function"},
            {"inputs": [{"components": [
                {"internalType": "address", "name": "tokenIn", "trade_type": "address"},
                {"internalType": "address", "name": "tokenOut", "trade_type": "address"},
                {"internalType": "uint24", "name": "fee", "trade_type": "uint24"},
                {"internalType": "address", "name": "recipient", "trade_type": "address"},
                {"internalType": "uint256", "name": "amountIn", "trade_type": "uint256"},
                {"internalType": "uint256", "name": "amountOutMinimum", "trade_type": "uint256"},
                {"internalType": "uint160", "name": "sqrtPriceLimitX96", "trade_type": "uint160"}],
                "internalType": "struct IV3SwapRouter.ExactInputSingleParams",
                "name": "params", "trade_type": "tuple"}],
                "name": "exactInputSingle", "outputs": [
                {"internalType": "uint256", "name": "amountOut", "trade_type": "uint256"}], "stateMutability": "payable",
                "trade_type": "function"},
            {"inputs": [{"components": [
                {"internalType": "bytes", "name": "path", "trade_type": "bytes"},
                {"internalType": "address", "name": "recipient", "trade_type": "address"},
                {"internalType": "uint256", "name": "amountOut", "trade_type": "uint256"},
                {"internalType": "uint256", "name": "amountInMaximum", "trade_type": "uint256"}],
                "internalType": "struct IV3SwapRouter.ExactOutputParams",
                "name": "params",
                "trade_type": "tuple"}],
                "name": "exactOutput",
                "outputs": [{
                    "internalType": "uint256",
                    "name": "amountIn",
                    "trade_type": "uint256"}],
                "stateMutability": "payable",
                "trade_type": "function"},
            {"inputs": [{"components": [{"internalType": "address", "name": "tokenIn", "trade_type": "address"},
                                           {"internalType": "address", "name": "tokenOut", "trade_type": "address"},
                                           {"internalType": "uint24", "name": "fee", "trade_type": "uint24"},
                                           {"internalType": "address", "name": "recipient", "trade_type": "address"},
                                           {"internalType": "uint256", "name": "amountOut", "trade_type": "uint256"},
                                           {"internalType": "uint256", "name": "amountInMaximum", "trade_type": "uint256"},
                                           {"internalType": "uint160", "name": "sqrtPriceLimitX96", "trade_type": "uint160"}],
                            "internalType": "struct IV3SwapRouter.ExactOutputSingleParams", "name": "params",
                            "trade_type": "tuple"}], "name": "exactOutputSingle",
                "outputs": [{"internalType": "uint256", "name": "amountIn", "trade_type": "uint256"}],
                "stateMutability": "payable", "trade_type": "function"},
            {"inputs": [], "name": "factory", "outputs": [{"internalType": "address", "name": "", "trade_type": "address"}],
             "stateMutability": "view", "trade_type": "function"},
            {"inputs": [], "name": "factoryV2", "outputs": [{"internalType": "address", "name": "", "trade_type": "address"}],
             "stateMutability": "view", "trade_type": "function"}, {
                "inputs": [{"internalType": "address", "name": "token", "trade_type": "address"},
                           {"internalType": "uint256", "name": "amount", "trade_type": "uint256"}], "name": "getApprovalType",
                "outputs": [{"internalType": "enum IApproveAndCall.ApprovalType", "name": "", "trade_type": "uint8"}],
                "stateMutability": "nonpayable", "trade_type": "function"}, {"inputs": [{"components": [
        {"internalType": "address", "name": "token0", "trade_type": "address"},
        {"internalType": "address", "name": "token1", "trade_type": "address"},
        {"internalType": "uint256", "name": "tokenId", "trade_type": "uint256"},
        {"internalType": "uint256", "name": "amount0Min", "trade_type": "uint256"},
        {"internalType": "uint256", "name": "amount1Min", "trade_type": "uint256"}],
        "internalType": "struct IApproveAndCall.IncreaseLiquidityParams",
        "name": "params", "trade_type": "tuple"}],
                "name": "increaseLiquidity", "outputs": [
            {"internalType": "bytes", "name": "result", "trade_type": "bytes"}], "stateMutability": "payable",
                "trade_type": "function"},
        {"inputs": [{"components": [{"internalType": "address", "name": "token0", "trade_type": "address"},
                                    {"internalType": "address", "name": "token1", "trade_type": "address"},
                                    {"internalType": "uint24", "name": "fee", "trade_type": "uint24"},
                                    {"internalType": "int24", "name": "tickLower", "trade_type": "int24"},
                                    {"internalType": "int24", "name": "tickUpper", "trade_type": "int24"},
                                    {"internalType": "uint256", "name": "amount0Min", "trade_type": "uint256"},
                                    {"internalType": "uint256", "name": "amount1Min", "trade_type": "uint256"},
                                    {"internalType": "address", "name": "recipient", "trade_type": "address"}],
                     "internalType": "struct IApproveAndCall.MintParams",
                     "name": "params",
                     "trade_type": "tuple"}],
                "name": "mint",
                "outputs": [{
                    "internalType": "bytes",
                    "name": "result",
                    "trade_type": "bytes"}],
                "stateMutability": "payable",
                "trade_type": "function"}, {
                "inputs": [{"internalType": "bytes32", "name": "previousBlockhash", "trade_type": "bytes32"},
                           {"internalType": "bytes[]", "name": "data", "trade_type": "bytes[]"}], "name": "multicall",
                "outputs": [{"internalType": "bytes[]", "name": "", "trade_type": "bytes[]"}], "stateMutability": "payable",
                "trade_type": "function"}, {"inputs": [{"internalType": "uint256", "name": "deadline", "trade_type": "uint256"},
                                                 {"internalType": "bytes[]", "name": "data", "trade_type": "bytes[]"}],
                                      "name": "multicall",
                                      "outputs": [{"internalType": "bytes[]", "name": "", "trade_type": "bytes[]"}],
                                      "stateMutability": "payable", "trade_type": "function"},
            {"inputs": [{"internalType": "bytes[]", "name": "data", "trade_type": "bytes[]"}], "name": "multicall",
             "outputs": [{"internalType": "bytes[]", "name": "results", "trade_type": "bytes[]"}],
             "stateMutability": "payable", "trade_type": "function"}, {"inputs": [], "name": "positionManager", "outputs": [
        {"internalType": "address", "name": "", "trade_type": "address"}], "stateMutability": "view", "trade_type": "function"}, {
                "inputs": [{"internalType": "address", "name": "token", "trade_type": "address"},
                           {"internalType": "uint256", "name": "value", "trade_type": "uint256"}], "name": "pull",
                "outputs": [], "stateMutability": "payable", "trade_type": "function"},
            {"inputs": [], "name": "refundETH", "outputs": [], "stateMutability": "payable", "trade_type": "function"}, {
                "inputs": [{"internalType": "address", "name": "token", "trade_type": "address"},
                           {"internalType": "uint256", "name": "value", "trade_type": "uint256"},
                           {"internalType": "uint256", "name": "deadline", "trade_type": "uint256"},
                           {"internalType": "uint8", "name": "v", "trade_type": "uint8"},
                           {"internalType": "bytes32", "name": "r", "trade_type": "bytes32"},
                           {"internalType": "bytes32", "name": "s", "trade_type": "bytes32"}], "name": "selfPermit",
                "outputs": [], "stateMutability": "payable", "trade_type": "function"}, {
                "inputs": [{"internalType": "address", "name": "token", "trade_type": "address"},
                           {"internalType": "uint256", "name": "nonce", "trade_type": "uint256"},
                           {"internalType": "uint256", "name": "expiry", "trade_type": "uint256"},
                           {"internalType": "uint8", "name": "v", "trade_type": "uint8"},
                           {"internalType": "bytes32", "name": "r", "trade_type": "bytes32"},
                           {"internalType": "bytes32", "name": "s", "trade_type": "bytes32"}], "name": "selfPermitAllowed",
                "outputs": [], "stateMutability": "payable", "trade_type": "function"}, {
                "inputs": [{"internalType": "address", "name": "token", "trade_type": "address"},
                           {"internalType": "uint256", "name": "nonce", "trade_type": "uint256"},
                           {"internalType": "uint256", "name": "expiry", "trade_type": "uint256"},
                           {"internalType": "uint8", "name": "v", "trade_type": "uint8"},
                           {"internalType": "bytes32", "name": "r", "trade_type": "bytes32"},
                           {"internalType": "bytes32", "name": "s", "trade_type": "bytes32"}],
                "name": "selfPermitAllowedIfNecessary", "outputs": [], "stateMutability": "payable",
                "trade_type": "function"}, {"inputs": [{"internalType": "address", "name": "token", "trade_type": "address"},
                                                 {"internalType": "uint256", "name": "value", "trade_type": "uint256"},
                                                 {"internalType": "uint256", "name": "deadline", "trade_type": "uint256"},
                                                 {"internalType": "uint8", "name": "v", "trade_type": "uint8"},
                                                 {"internalType": "bytes32", "name": "r", "trade_type": "bytes32"},
                                                 {"internalType": "bytes32", "name": "s", "trade_type": "bytes32"}],
                                      "name": "selfPermitIfNecessary", "outputs": [], "stateMutability": "payable",
                                      "trade_type": "function"}, {
                "inputs": [{"internalType": "uint256", "name": "amountIn", "trade_type": "uint256"},
                           {"internalType": "uint256", "name": "amountOutMin", "trade_type": "uint256"},
                           {"internalType": "address[]", "name": "path", "trade_type": "address[]"},
                           {"internalType": "address", "name": "to", "trade_type": "address"}],
                "name": "swapExactTokensForTokens",
                "outputs": [{"internalType": "uint256", "name": "amountOut", "trade_type": "uint256"}],
                "stateMutability": "payable", "trade_type": "function"}, {
                "inputs": [{"internalType": "uint256", "name": "amountOut", "trade_type": "uint256"},
                           {"internalType": "uint256", "name": "amountInMax", "trade_type": "uint256"},
                           {"internalType": "address[]", "name": "path", "trade_type": "address[]"},
                           {"internalType": "address", "name": "to", "trade_type": "address"}],
                "name": "swapTokensForExactTokens",
                "outputs": [{"internalType": "uint256", "name": "amountIn", "trade_type": "uint256"}],
                "stateMutability": "payable", "trade_type": "function"}, {
                "inputs": [{"internalType": "address", "name": "token", "trade_type": "address"},
                           {"internalType": "uint256", "name": "amountMinimum", "trade_type": "uint256"},
                           {"internalType": "address", "name": "recipient", "trade_type": "address"}], "name": "sweepToken",
                "outputs": [], "stateMutability": "payable", "trade_type": "function"}, {
                "inputs": [{"internalType": "address", "name": "token", "trade_type": "address"},
                           {"internalType": "uint256", "name": "amountMinimum", "trade_type": "uint256"}],
                "name": "sweepToken", "outputs": [], "stateMutability": "payable", "trade_type": "function"}, {
                "inputs": [{"internalType": "address", "name": "token", "trade_type": "address"},
                           {"internalType": "uint256", "name": "amountMinimum", "trade_type": "uint256"},
                           {"internalType": "uint256", "name": "feeBips", "trade_type": "uint256"},
                           {"internalType": "address", "name": "feeRecipient", "trade_type": "address"}],
                "name": "sweepTokenWithFee", "outputs": [], "stateMutability": "payable", "trade_type": "function"}, {
                "inputs": [{"internalType": "address", "name": "token", "trade_type": "address"},
                           {"internalType": "uint256", "name": "amountMinimum", "trade_type": "uint256"},
                           {"internalType": "address", "name": "recipient", "trade_type": "address"},
                           {"internalType": "uint256", "name": "feeBips", "trade_type": "uint256"},
                           {"internalType": "address", "name": "feeRecipient", "trade_type": "address"}],
                "name": "sweepTokenWithFee", "outputs": [], "stateMutability": "payable", "trade_type": "function"}, {
                "inputs": [{"internalType": "int256", "name": "amount0Delta", "trade_type": "int256"},
                           {"internalType": "int256", "name": "amount1Delta", "trade_type": "int256"},
                           {"internalType": "bytes", "name": "_data", "trade_type": "bytes"}],
                "name": "uniswapV3SwapCallback", "outputs": [], "stateMutability": "nonpayable", "trade_type": "function"}, {
                "inputs": [{"internalType": "uint256", "name": "amountMinimum", "trade_type": "uint256"},
                           {"internalType": "address", "name": "recipient", "trade_type": "address"}], "name": "unwrapWETH9",
                "outputs": [], "stateMutability": "payable", "trade_type": "function"},
            {"inputs": [{"internalType": "uint256", "name": "amountMinimum", "trade_type": "uint256"}], "name": "unwrapWETH9",
             "outputs": [], "stateMutability": "payable", "trade_type": "function"}, {
                "inputs": [{"internalType": "uint256", "name": "amountMinimum", "trade_type": "uint256"},
                           {"internalType": "address", "name": "recipient", "trade_type": "address"},
                           {"internalType": "uint256", "name": "feeBips", "trade_type": "uint256"},
                           {"internalType": "address", "name": "feeRecipient", "trade_type": "address"}],
                "name": "unwrapWETH9WithFee", "outputs": [], "stateMutability": "payable", "trade_type": "function"}, {
                "inputs": [{"internalType": "uint256", "name": "amountMinimum", "trade_type": "uint256"},
                           {"internalType": "uint256", "name": "feeBips", "trade_type": "uint256"},
                           {"internalType": "address", "name": "feeRecipient", "trade_type": "address"}],
                "name": "unwrapWETH9WithFee", "outputs": [], "stateMutability": "payable", "trade_type": "function"},
            {"inputs": [{"internalType": "uint256", "name": "value", "trade_type": "uint256"}], "name": "wrapETH",
             "outputs": [], "stateMutability": "payable", "trade_type": "function"},
            {"stateMutability": "payable", "trade_type": "receive"}]
